apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-restore-config
  namespace: <namespace>
data:
  mongo-restore.sh: |
    #!/bin/bash

    # Install Curl
    apt update && apt install curl

    # Add the Cloud SDK distribution URI as a package source
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" |  tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

    # Import the Google Cloud Platform public key
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |  apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

    # Update the package list
    apt-get update

    # Install the Google Cloud SDK
    apt-get install google-cloud-sdk

    # Authenticate
    export GOOGLE_APPLICATION_CREDENTIALS=$SERVICE_ACCOUNT_JSON

    # Latest backup object
    latest_backup=$(gsutil ls -l gs://$BUCKET_NAME/ | sed '$d' | tail -n 1 | awk '{print $3}')

    # Copy the latest backup to the local directory
    gsutil cp "${latest_backup}" .

    # Filename 
    backup_path=$(basename $latest_backup)

    # Extract database from backup from tar
    tar -xvf $backup_path 

    # Select the primary node for write operations
    primary_node=$(mongosh --host "$MONGODB_HOST" --port 27017 --username "$MONGODB_USER" --password "$MONGODB_PASSWORD" --eval "rs.isMaster().primary" --quiet)

    # Sync staging clockbook-app-prod database to prod
    mongorestore --host "$primary_node" --port 27017 --username "$MONGODB_USER" --password "$MONGODB_PASSWORD" --authenticationDatabase admin --drop --db <database-name> <path-to-backup-for this database>
